accounts/urls.py
from accounts.views import AccountCreateView, AccountLoginView, AccountLogoutView, \
    AccountPasswordChangeView, AccountUpdateView


from django.urls import path


app_name = 'accounts'

urlpatterns = [
    path('register/', AccountCreateView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', AccountPasswordChangeView.as_view(), name='password'),
    ]

app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # UI
    path('admin/', admin.site.urls, name='admin'),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    ]

handler404 = views.error_404
handler400 = views.error_400
handler403 = views.error_403
handler500 = views.error_500

accounts/models.py
import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

core/models.py
from django.db import models


class BaseModel(models.Model):
    class Meta:
        abstract = True

    create_date = models.DateTimeField(null=True, auto_now_add=True)
    write_date = models.DateTimeField(null=True, auto_now=True)

accounts/forms.py
from accounts.models import User

from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm, UserCreationForm


class AccountCreateForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = ['username', 'password1', 'password2']


class AccountUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name']


class AccountPasswordChangeForm(PasswordChangeForm):
    pass

accounts/views.py
from accounts.forms import AccountCreateForm, AccountPasswordChangeForm, AccountUpdateForm
from accounts.models import User

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView


class AccountCreateView(CreateView):
    """Create Account"""
    model = User
    template_name = 'registration.html'
    form_class = AccountCreateForm
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, 'you have successfully registered')
        return result


class AccountLoginView(LoginView):
    """account login"""
    template_name = 'login.html'

    def get_redirect_url(self):
        if self.request.GET.get('next'):
            return self.request.GET.get('next')
        else:
            return reverse('core:index')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, 'you have successfully logged in')
        return result


class AccountLogoutView(LogoutView):
    """Account Logout"""
    template_name = 'logout.html'

    def get_next_page(self):
        result = super().get_next_page()
        messages.success(self.request, 'you have successfully logged out')
        return result


class AccountUpdateView(UpdateView):
    """Account Update"""
    model = User
    template_name = 'profile.html'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('core:index')

    def get_object(self, queryset=None):
        return self.request.user


class AccountPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    """change account password"""
    template_name = 'password-change.html'
    form_class = AccountPasswordChangeForm
    success_url = reverse_lazy('core:index')

core/views.py
from django.shortcuts import render


def index(request):
    """main page"""

    return render(
        request=request,
        template_name='index.html'
    )


def error_404(request,  exception):
    data = {}
    return render(request, '404.html', data)


def error_500(request):
    data = {}
    return render(request, '500.html', data)


def error_403(request, exception):
    data = {}
    return render(request, '403.html', data)


def error_400(request,  exception):
    data = {}
    return render(request, '400.html', data)

accounts/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title%}
    <title>Login as a new user</title>
{% endblock %}

{% block header%}
<h3>Login as a new user</h3>
{% endblock %}

{% block content %}

    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <input type="submit" class="btn btn-success" value="Log in">
        <a class="btn btn-light" href="{% url 'core:index' %}">Home</a>
    </form>

{% endblock %}

accounts/templates/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title%}
    <title>Logged out</title>
{% endblock %}

{% block header%}
<h3>User is logged out</h3>
{% endblock %}

{% block content %}

        <a class="btn btn-light" href="{% url 'accounts:login' %}">Login</a>
        <a class="btn btn-light" href="{% url 'core:index' %}">Home</a>

{% endblock %}

accounts/templates/password-change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title%}
    <title>Change password</title>
{% endblock %}

{% block header%}
<h3>Change password</h3>
{% endblock %}

{% block content %}

    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <input type="submit" class="btn btn-success" value="change password">
        <a class="btn btn-light" href="{% url 'core:index' %}">Cancel</a>
    </form>

{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title%}
    <title>Edit user</title>
{% endblock %}

{% block header%}
<h3>Edit user</h3>
{% endblock %}

{% block content %}

    <form method="post" enctype="multipart/form-data">

        <div class="media">
            <div class="media-body p-3 m-3">
                <h2 class="account-heading">{{ user.username }}</h2>
                <h3 class="account-heading">{{ user.first_name }} {{ user.last_name }} </h3>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>


        {% csrf_token %}

        {{form|crispy}}

        <input type="submit" class="btn btn-success" value="Save">
        <a class="btn btn-light" href="{% url 'core:index' %}">Cancel</a>
    </form>

{% endblock %}

accounts/templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title%}
    <title>Register new user</title>
{% endblock %}

{% block header%}
<h3>Register new user</h3>
{% endblock %}

{% block content %}

    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <input type="submit" class="btn btn-success" value="Register">
        <a class="btn btn-light" href="{% url 'core:index' %}">Home</a>
    </form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">


<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<!-- XDSoft DateTimePicker -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>


{% block title%}
    <title>Test name</title>
{% endblock %}
<style type="text/css">

* {
  margin: 0;
  padding: 0;
}

.c {
    font-size: 50%;
    background: #faf0e6; /* Цвет фона */
    border: 1px solid #01796f; /* Рамка */
    border-radius: 15px;
    display: inline-block;
    padding: 5px 15px; /* Поля */
    text-decoration: none; /* Убираем подчёркивание */
    color: #01796f; /* Цвет текста */
}

body {
    height: 100%;
    background: url({% static "common/img/bg1.jpg" %}) no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    background-attachment: fixed;
       }
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}

.wrapper {
  height: 100%;
}

.content {
  box-sizing: border-box;
  min-height: 100%;
  padding-bottom: 90px;

</style>
</head>

<body>

{%url 'accounts:users' as Users %}
{%url 'accounts:profile' as Profile %}
{%url 'accounts:register' as Register %}
{%url 'accounts:login' as Login %}


<nav class="navbar navbar-expand-lg navbar-primary bg-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'core:index' %}">Test name</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
<!--          <li class="nav-item active">-->
<!--            <a class="nav-link" href=#">Test<span class="sr-only">(current)</span></a>-->
<!--          </li>-->
<!--            <li class="nav-item active">-->
<!--            <a class="nav-link" href=#>Test<span class="sr-only">(current)</span></a>-->
<!--          </li>-->
<!--          <li class="nav-item active">-->
<!--            <a class="nav-link" href=#">Test</a>-->
<!--          </li>-->
    <!--      <li class="nav-item dropdown">-->
    <!--        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
    <!--          Dropdown-->
    <!--        </a>-->
    <!--        <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
    <!--          <a class="dropdown-item" href="#">Action</a>-->
    <!--          <a class="dropdown-item" href="#">Another action</a>-->
    <!--          <div class="dropdown-divider"></div>-->
    <!--          <a class="dropdown-item" href="#">Something else here</a>-->
    <!--        </div>-->
    <!--      </li>-->
    <!--      <li class="nav-item">-->
    <!--        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
    <!--      </li>-->
        </ul>
    <!--    <form class="form-inline my-2 my-lg-0">-->
    <!--      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
    <!--      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
    <!--    </form>-->
            <ul class="navbar-nav">

                {% if user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
                </li>

                <li class="nav-item {% if request.path == Profile %} active {% endif %}">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">Profile ({{ user.username }})</a>
                </li>

                {% else %}

                <li class="nav-item {% if request.path == Register %} active {% endif %}">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                </li>

                <li class="nav-item {% if request.path == Login %} active {% endif %}">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>


                {% endif %}

                {% if user.is_superuser %}

                <li>
                    <a class="nav-link" href="{% url 'admin:index' %}">admin</a>
                </li>

                {% endif %}

            </ul>
      </div>
    </div>
</nav>


{% include 'includes/messages.html' %}

<div class="wrapper">

    <div class="content">

        <div class="container">
            <div class="border border-white rounded-pill shadow p-3 mb-5 mt-5 bg-white rounded text-center">
                {% block header %}
                {% endblock %}
            </div>
            {% block video %}
            {% endblock %}

            {% block content %}
            {% endblock %}

        </div><br>

    </div>

</div>

</body>
</html>

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/includes/pagination.html
<br>
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ request.query_params }}">previous</a></li>
        {% endif %}

        <li class="page-link" >
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </li>

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ request.query_params }}">next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last</a></li>
        {% endif %}
    </ul>
</nav>

templates/index.html
{% extends 'base.html' %}
{% load static %}